[package]
name = "agate"
version = "1.1.0"
authors = ["Matt Brubeck <mbrubeck@limpet.net>"]
description = "Very simple server for the Gemini hypertext protocol"
keywords = ["server", "gemini", "hypertext", "internet", "protocol"]
categories = ["network-programming"]
repository = "https://github.com/mbrubeck/agate"
readme = "README.md"
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
async-tls = "0.7.0"
async-std = "1.5"
futures = "0.3.5"
once_cell = "1.4"
rustls = "0.17.0"
tree_magic = "0.2.3"
url = "2.1"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[patch.crates-io.tree_magic]
git = "https://github.com/mbrubeck/tree_magic"
branch = "override"
